// <auto-generated />
using System;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20251104123136_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FinalKey")
                        .HasColumnType("text")
                        .HasColumnName("final_key");

                    b.Property<string>("MediaData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("media_data");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("RawKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("media_assets", (string)null);

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.Entities.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Entities.MediaAsset");

                    b.HasDiscriminator().HasValue("Preview");
                });

            modelBuilder.Entity("FileService.Domain.Entities.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Entities.MediaAsset");

                    b.Property<string>("HlsRootKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hls_root_key");

                    b.HasDiscriminator().HasValue("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
